### ISSUE TITLE
`stub` directory

### ISSUE THREAD

**Issue by mikemand** [ssx/skrub#7]
Some packages use the `stub` directory in their file generators (Laravel Dusk (when generating a new test), Laravel Horizon (on installation; for customizing who can access), Laravel Telescope (on installation; for customizing who can access), etc.). An option to ignore removing this directory would be awesome.

Example paths:

```
path: ./vendor/laravel/telescope/stubs
name: stubs
is directory: ./vendor/laravel/telescope/stubs
 
path: ./vendor/laravel/horizon/stubs
name: stubs
is directory: ./vendor/laravel/horizon/stubs
 
path: ./vendor/laravel/dusk/stubs
name: stubs
is directory: ./vendor/laravel/dusk/stubs
```

**Comment by ssx** [comment]
agreed. This would make a great candidate to remove. Will add it in.


From: Micheal Mand <notifications@github.com> <notifications@github.com>
Reply: ssx/skrub
<reply@reply.github.com>
<reply@reply.github.com>
Date: 8 October 2019 at 16:48:53
To: ssx/skrub <skrub@noreply.github.com> <skrub@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
<subscribed@noreply.github.com>
Subject:  [ssx/skrub] `stub` directory (#7)

Some packages use the stub directory in their file generators (Laravel Dusk

**Comment by ssx** [comment]
Hi @mikemand, this is already present in the remove list: https://github.com/ssx/skrub/blob/master/src/SkrubCommand.php#L47

**Comment by mikemand** [comment]
@ssx, right...It's being removed when it shouldn't be. Without the `stubs` directory, creating new Dusk tests via generator fails.

**Comment by ssx** [comment]
Ah, gotcha! We’ll take that out for now then. :)


From: Micheal Mand <notifications@github.com> <notifications@github.com>
Reply: ssx/skrub
<reply@reply.github.com>
<reply@reply.github.com>
Date: 22 October 2019 at 18:54:38
To: ssx/skrub <skrub@noreply.github.com> <skrub@noreply.github.com>
CC: Scott Robinson <scott@dor.ky> <scott@dor.ky>, Mention
<mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [ssx/skrub] `stub` directory (#7)

@ssx <https://github.com/ssx>, right...It's being removed when it shouldn't

**Comment by ssx** [comment]
@mikemand: fixed in https://github.com/ssx/skrub/commit/46f6e8fc1e72be47908c44f5cf228dd95de6a468

**Comment by mikemand** [comment]
Thank you! 👍
